### ISSUE TITLE
the script is sending just to 10 members 

### ISSUE THREAD

**Issue by DRL7N** [juanmicl/DiscordMassDM#2]
the script is sending just to 10 members

**Comment by juanmicl** [comment]
your account should be banned. You have to increase the sleep time.

**Comment by DRL7N** [comment]
yes i know but this script is sending to 10 members and timeout

**Comment by juanmicl** [comment]
yes, because you have a timeout limit on your php.ini settings.

Please run it on console and all timeout problems will be solved :)
